### ISSUE TITLE
Cant get this to work.

### ISSUE THREAD

**Issue by proper-systems** [Soneso/stellar-php-sdk#1]
I cant get any example to even work because there are no examples that even run auto loader with correct includes.

I know composer is wonderful but I always have problems getting it working.

Just add functional examples - that load things they need to run.

Examples listed 
```
// create a completely new and unique pair of keys.
$keyPair = KeyPair::random();

print($keyPair->getAccountId());
// GCFXHS4GXL6BVUCXBWXGTITROWLVYXQKQLF4YH5O5JT3YZXCYPAFBJZB

print($keyPair->getSecretSeed());
// SAV76USXIJOBMEQXPANUOQM6F5LIOTLPDIDVRJBFFE2MDJXG24TAPUU7
```
And I get:

Fatal error: Uncaught Error: Class 'KeyPair' not found in

How am i suposed to know what to include to bring this class in?

**Comment by srdante** [comment]
This is related to your knowledge with composer and auto-loader and not an issue with the package.

You need to find the classes using your IDE suggestions or navigating the package files.

```
use Soneso\StellarSDK\Crypto\KeyPair;
```

**Comment by proper-systems** [comment]
Agreed I hate composer and whole deployment garbage 

I wrote my own functions.

**Comment by danbradster** [comment]
> This is related to your knowledge with composer and auto-loader and not an issue with the package.
> 
> You need to find the classes using your IDE suggestions or navigating the package files.
> 
> ```
> use Soneso\StellarSDK\Crypto\KeyPair;
> ```

`<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require('autoload.php');

use Soneso\StellarSDK\Crypto\KeyPair;


$keyPair = KeyPair::random();
print($keyPair->getAccountId());
print($keyPair->getSecretSeed());
?>`

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/equitiescharts/equitiescharts.com/soneso/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Crypto/KeyPair.php on line 32`
