### ISSUE TITLE
Set home domain

### ISSUE THREAD

**Issue by nash81** [Soneso/stellar-php-sdk#10]
Hi is there a method to set the home domain when we create our own assets ?

**Comment by christian-rogobete** [comment]
Hello @nash81, thank you for your message. Yes, you can set it by using the set options operation. See for example here in the tests off the sdk, how we did it:
https://github.com/Soneso/stellar-php-sdk/blob/main/Soneso/StellarSDKTests/AccountTest.php#L46

For the future, please consider, that the issue tracker here is for reporting bugs or issues with the sdk. 
If you need consulting you can contact us via our homepage www.soneso.com or simply ask your questions in the official stellar developers discord channel.
