### ISSUE TITLE
Not able to hide errors

### ISSUE THREAD

**Issue by angelscry** [Soneso/stellar-php-sdk#12]
I'm actually trying to check if an account address exist on not :
```
<?php

ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
error_reporting(0);

require('autoload.php');
use Soneso\StellarSDK\Asset;
use Soneso\StellarSDK\StellarSDK;
use Soneso\StellarSDK\Exceptions\HorizonRequestException;

$accountId = "GBEJWZEYDCJIKBW7PZKIJPRHD6WSPNETCEDV5UWRLDBLKXA7QT2DTLVF";
$sdk = StellarSDK::getPublicNetInstance();

try {
    $account = $sdk->requestAccount($accountId);
    echo 'Account found!';
} catch (HorizonRequestException $e) {
    echo 'Error: '. $e->getMessage();
}

?>
```
Address GBEJWZEYDCJIKBW7PZKIJPRHD6WSPNETCEDV5UWRLDBLKXA7QT2DTLVF did not exist, so I expect to obtain : 
```
Error: The request you sent was invalid in some way.
```
Instead I obtain : 
```
{ "type": "https://stellar.org/horizon-errors/bad_request", "title": "Bad Request", "status": 400, "detail": "The request you sent was invalid in some way.", "extras": { "invalid_field": "account_id", "reason": "Account ID must start with `G` and contain 56 alphanum characters" } } Error: The request you sent was invalid in some way.
```
What is wrong ?

**Comment by christian-rogobete** [comment]
Hi @angelscry,

your account id is invalid, it has an invalid checksum.

You can see the same result if you use it in [stellar laboratory](https://laboratory.stellar.org/)

```php
$kp = KeyPair::fromAccountId("GBEJWZEYDCJIKBW7PZKIJPRHD6WSPNETCEDV5UWRLDBLKXA7QT2DTLVF");
```
will also fail with:

```php
InvalidArgumentException : invalid checksum in encoded data
```

**Comment by angelscry** [comment]
Hi @christian-rogobete

Thank you for you quick reply. I think I expressed myself badly... Sorry...

Basically I want to test if an account id is valid or not by only using stellar-php-sdk. The account id into my script example is voluntarily wrong.  As it is wrong, I want to be able to handle the corresponding error message. In my script I expected to only display : 

`Error: The request you sent was invalid in some way.`
 
But it actually display : 

`{ "type": "https://stellar.org/horizon-errors/bad_request", "title": "Bad Request", "status": 400, "detail": "The request you sent was invalid in some way.", "extras": { "invalid_field": "account_id", "reason": "Account ID must start with `G` and contain 56 alphanum characters" } } Error: The request you sent was invalid in some way.`

How to not have `{ "type": "https://stellar.org/horizon-errors/bad_request", "title": "Bad Request", "status": 400, "detail": "The request you sent was invalid in some way.", "extras": { "invalid_field": "account_id", "reason": "Account ID must start with `G` and contain 56 alphanum characters" } }` displayed?

I have try to hide error messages and handle error messages, but it did not work. Or maybe I do something wrong...

**Comment by angelscry** [comment]
Ho... That's effectively a more simple way to proceed.
Thank you.

**Comment by christian-rogobete** [comment]
yw
