### ISSUE TITLE
Bug in SetOptionsOperation

### ISSUE THREAD

**Issue by eugene3141** [Soneso/stellar-php-sdk#15]
https://github.com/Soneso/stellar-php-sdk/blob/69a3894279d794690c24352804aca9980643e55b/Soneso/StellarSDK/SetOptionsOperation.php#L181
It's impossible to set masterKeyWeight to 0. It should be
```
 if ($this->masterKeyWeight !== null) {
   $result->setMasterWeight($this->masterKeyWeight);
 }
```

**Comment by christian-rogobete** [comment]
Hello @eugene3141,
thank you for reporting this issue. I fixed it in release 1.0.2

**Comment by eugene3141** [comment]
https://onlinephp.io?s=s7EvyCjg5eLlUilLLFKwVTCwBnEy0zTAfEVbhbzSnBxNhWpeLs7U5Ix8BXUDmKA6UGUtqmLsqpGUAwA%2C&v=8.1.11

`!=` doesn't check type, so int 0 equals null, and the check fails.
It should be `!==` to force type check.

**Comment by christian-rogobete** [comment]
thx, it's strange because it worked in my test. I updated it in release 1.0.3.

**Comment by eugene3141** [comment]
Thank you.
In the test, you used assertEquals, it also doesn't check type.
assertSame checks type.

**Comment by christian-rogobete** [comment]
thank you
