### ISSUE TITLE
txRep

### ISSUE THREAD

**Issue by JohnGabrielRodi** [Soneso/stellar-php-sdk#18]
Maybe I found a bug?

    $txRep = TxRep::fromTransactionEnvelopeXdrBase64($data);
    print "Transaction Result:  ";
    print($txRep);
    echo "<br><br>";
    
    
    echo "<br><br>";
    $envelope = TxRep::transactionEnvelopeXdrBase64FromTxRep($txRep);
    print "Transaction Envelope:  ";
    print_r($envelope);
    echo "<br><br>";

Result of first operation is:

Transaction Result: type: ENVELOPE_TYPE_TX tx.sourceAccount: GBGZGXYWXZ65XBD4Q4UTOMIDXRZ5X5OJGNC54IQBLSPI2DDB5VGFZO2V tx.fee: 6000 tx.seqNum: 5628434382323746 tx.cond.type: PRECOND_NONE tx.memo.type: MEMO_NONE tx.operations.len: 1 tx.operations[0].sourceAccount._present: false tx.operations[0].body.type: PAYMENT tx.operations[0].body.paymentOp.destination: GD53ZDEHFQPY25NBF6NPDYEA5IWXSS5FYMLQ3AE6AIGAO75XQK7SIVNU tx.operations[0].body.paymentOp.asset: XLM tx.operations[0].body.paymentOp.amount: 100000000 tx.ext.v: 0 signatures.len: 1 signatures[0].hint: 61ed4c5c signatures[0].signature: bd33b8de6ca4354d653329e4cfd2f012a3c155c816bca8275721bd801defb868642e2cd49330e904d2df270b4a2c95359536ba81eed9775c5982e411ac9c3909

But the reverse gives an error:
Fatal error: Uncaught InvalidArgumentException: invalid tx.timeBounds in C:\xampp\htdocs\sophia_survey\vendor\soneso\stellar-php-sdk\Soneso\StellarSDK\SEP\TxRep\TxRep.php:493 Stack trace: #0 C:\xampp\htdocs\sophia_survey\vendor\soneso\stellar-php-sdk\Soneso\StellarSDK\SEP\TxRep\TxRep.php(475): Soneso\StellarSDK\SEP\TxRep\TxRep::parseTimeBounds(Array, 'tx.') #1 C:\xampp\htdocs\sophia_survey\vendor\soneso\stellar-php-sdk\Soneso\StellarSDK\SEP\TxRep\TxRep.php(256): Soneso\StellarSDK\SEP\TxRep\TxRep::parsePreconditions(Array, 'tx.') #2 C:\xampp\htdocs\sophia_survey\payment4.php(180): Soneso\StellarSDK\SEP\TxRep\TxRep::transactionEnvelopeXdrBase64FromTxRep('type: ENVELOPE_...') #3 {main} thrown in C:\xampp\htdocs\sophia_survey\vendor\soneso\stellar-php-sdk\Soneso\StellarSDK\SEP\TxRep\TxRep.php on line 493

This is on testnet.

**Comment by christian-rogobete** [comment]
Hello @JohnGabrielRodi 
thank you for adding this issue. Yes it seams to be a bug. TimeBounds should be optional. I will fix is asap and will let you know.
Thx!

**Comment by christian-rogobete** [comment]
fixed in [release 1.0.5](https://github.com/Soneso/stellar-php-sdk/releases/tag/1.0.5)
