### ISSUE TITLE
Could not unmarshall transaction

### ISSUE THREAD

**Issue by DaanKrug** [Soneso/stellar-php-sdk#26]
This seems to be the same case related on other Stellar libraries as this for example:
https://github.com/stellar/js-soroban-client/issues/84

After some debugs on code I found that makes sense to be related to question above. I only do not understood why, if I am only replicating the same unit tests that comes with this library. Maybe the TestNet (futurenet) was upgraded after the library last release?

![error_001](https://github.com/Soneso/stellar-php-sdk/assets/26380119/f4ede4ef-67ac-4dd7-8a21-aa44b5f0811c)
![error_002](https://github.com/Soneso/stellar-php-sdk/assets/26380119/8290988c-1a16-4e2a-bf83-420ed454d320)

This is my composer.json
![error_003](https://github.com/Soneso/stellar-php-sdk/assets/26380119/3918fd80-23c5-436a-becf-eab40bf60500)

**Comment by christian-rogobete** [comment]
Hello @DaanKrug thank you for adding this issue. The SDK must be updated to support the new soroban prev. 10. I am working on it and I will publish a new version this weekend.

**Comment by DaanKrug** [comment]
Here the postman collection and composer.json:
[Soroban.postman_collection.zip](https://github.com/Soneso/stellar-php-sdk/files/12126646/Soroban.postman_collection.zip)
[composer.zip](https://github.com/Soneso/stellar-php-sdk/files/12126664/composer.zip)

**Comment by DaanKrug** [comment]
Hello @christian-rogobete, thank you and your team for this very great work on this library. I mean this will improve a lot the adoption of this crypto network.

**Comment by christian-rogobete** [comment]
Hello @DaanKrug you are welcome. Thank you for the nice words, they motivate me to continue improving and extending the SDK.

**Comment by christian-rogobete** [comment]
Hello @DaanKrug, it should be fixed with [release 1.2.3](https://github.com/Soneso/stellar-php-sdk/releases/tag/1.2.3)

**Comment by DaanKrug** [comment]
Closing.
