### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by danbradster** [Soneso/stellar-php-sdk#3]
I can't work out the includes etc.

I see directories - 
/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK

I put a php file in /vendor/

This code just crashes error 500 - 

```
<?php
require('autoload.php');

use Soneso\StellarSDK\Asset;
use Soneso\StellarSDK\AssetTypeCreditAlphanum4;
use Soneso\StellarSDK\ChangeTrustOperationBuilder;
use Soneso\StellarSDK\CreateAccountOperationBuilder;
use Soneso\StellarSDK\Crypto\KeyPair;
use Soneso\StellarSDK\ManageDataOperationBuilder;
use Soneso\StellarSDK\ManageSellOfferOperationBuilder;
use Soneso\StellarSDK\MuxedAccount;
use Soneso\StellarSDK\Network;
use Soneso\StellarSDK\PathPaymentStrictReceiveOperationBuilder;
use Soneso\StellarSDK\PathPaymentStrictSendOperationBuilder;
use Soneso\StellarSDK\PaymentOperationBuilder;
use Soneso\StellarSDK\Responses\Operations\CreateAccountOperationResponse;
use Soneso\StellarSDK\Responses\Operations\PaymentOperationResponse;
use Soneso\StellarSDK\StellarSDK;
use Soneso\StellarSDK\TransactionBuilder;
use Soneso\StellarSDK\Util\FriendBot;


$keyPair = KeyPair::random();
print($keyPair->getAccountId());
print($keyPair->getSecretSeed());
?>
```

**Comment by danbradster** [comment]
Worked it out.

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

Above fixed the error 500.  Then got - 

`syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`

Worked out that my PHP was 7.3 but it should be 7.4 to fix this error.

**Comment by danbradster** [comment]
New error - 

`Parse error: syntax error, unexpected '|', expecting ';' or '{' in /soneso/vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Price.php on line 46`

Which seems to be this line - 

`public static function fromString(string $price) : Price | false {`

Code:

`$amountSelling = "0.000001";
$price = "1.5";
//ERROR HERE
$ms = (new ManageSellOfferOperationBuilder($asset1, $asset2, $amountSelling, $price))->build();`

**Comment by danbradster** [comment]
![image](https://user-images.githubusercontent.com/5838187/158301508-5acb18ce-f244-4c52-8e74-2f53f049c932.png)

**Comment by mahho** [comment]
Use php8
