### ISSUE TITLE
Package [phpseclib/phpseclib] is not locked at minimum working release 3.0.*

### ISSUE THREAD

**Issue by joemags-apps** [Soneso/stellar-php-sdk#30]
Error: Class "phpseclib3\Math\BigInteger" not found {"exception":"[object] (Error(code: 0): Class \"phpseclib3\\Math\\BigInteger\" not found at .../vendor/soneso/stellar-php-sdk/Soneso/StellarSDK/Xdr/XdrBuffer.php:67)

I have another package that requires phpseclib version ^2 but this one is not raising conflict, so if run with -W or run `composer update` it gets downgraded 

![image](https://github.com/Soneso/stellar-php-sdk/assets/63977646/ef624564-4b56-423c-b3b9-c153903aba38)

Suggestion: Lock `phpseclib/phpseclib` to ^3 so that it raises conflict

**Comment by christian-rogobete** [comment]
Hello @joemags-apps, thank you for adding this issue. I changed it to ^3. in the new [release 1.2.5](https://github.com/Soneso/stellar-php-sdk/releases/tag/1.2.5)
