### ISSUE TITLE
Call to a member function getAccountId() on null

### ISSUE THREAD

**Issue by eugene3141** [Soneso/stellar-php-sdk#7]
https://github.com/Soneso/stellar-php-sdk/blob/b3d7631fdfd79484b492673054be9e877abae40d/Soneso/StellarSDK/SetOptionsOperation.php#L153
When inflationDestination is null we get the error "Call to a member function getAccountId() on null".

**Comment by christian-rogobete** [comment]
Hi @eugene3141, thank you for reporting this issue. I fixed it in [release 0.7.1](https://github.com/Soneso/stellar-php-sdk/releases/tag/0.7.1)
