### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by eugene3141** [Soneso/stellar-php-sdk#8]
https://github.com/Soneso/stellar-php-sdk/blob/2734e2f42d6f4d589efe76c3e6b8cf4aab5d59a5/Soneso/StellarSDK/Transaction.php#L158
There are situations where a transaction envelope could be without signatures. For example, if I want to pass the XDR to a user for signing. So this exception is unnecessary.

https://github.com/Soneso/stellar-php-sdk/blob/2734e2f42d6f4d589efe76c3e6b8cf4aab5d59a5/Soneso/StellarSDK/TransactionPreconditions.php#L136
If the ledger bounds or the time bounds aren't set, we get the null exception.

**Comment by christian-rogobete** [comment]
Hello @eugene3141,

thank you for adding this issue. I addressed it in [release 0.7.2](https://github.com/Soneso/stellar-php-sdk/releases/tag/0.7.2)
