### ISSUE TITLE
Get Asset Images

### ISSUE THREAD

**Issue by nash81** [Soneso/stellar-php-sdk#9]
Hi, 
Is there a way we can get the image of an asset when seeing the account balance?

**Comment by christian-rogobete** [comment]
Hey @nash81, 
you can check the SEP001 implementation:
https://github.com/Soneso/stellar-php-sdk/blob/main/examples/sep-0001-toml.md
1. find the asset issuer id form the account balance
2. load the details of the account issuer id and check if it has an home domain stored
3. if it has a home domain you can use the sep001 implementation to check if the provide an image for it

E.g. AQUA:
https://aqua.network/.well-known/stellar.toml

Best 
C
